frontend/babel.config.json
frontend/index.html
frontend/package.json
frontend/src/index.tsx
frontend/src/tsconfig.json
frontend/webpack.config.js
frontend/yarn.lock

개발환경에 필요한 typscript, webpack loader, plugin 설정을 진행했습니다. 
- [webpack guide](https://webpack.kr/guides/development/) 에 따라서 빌드 설정
- typescript setup

build: setup development environment

---

backend/.idea/modules.xml
backend/.idea/modules/demo.main.iml
backend/src/main/java/ossproj/demo/entity/Lecture.java
backend/src/main/java/ossproj/demo/entity/Major.java
backend/src/main/java/ossproj/demo/entity/Professor.java
backend/src/main/java/ossproj/demo/entity/Timetable.java
backend/src/main/java/ossproj/demo/entity/User.java
backend/src/main/java/ossproj/demo/repository/LectureRepository.java

각 엔티티의 수정사항을 반영하고, 교수 및 조합시간표 엔티티를 구현했습니다.
DB 테이블 엔티티 구현

feat: 조합 시간표 엔티티 생성 및 빌더 구현

---

.github/workflows/main.yml

build: add cicd yml

---

.github/workflows/main.yml

build: add backend build test script
백엔드 CICD 스크립트 작성

build: add backend build test script

---

.github/workflows/main.yml

fix: delete main.yml deploy code line
빌드시 주석처리한 프론트 needs 제거

fix: delete main.yml deploy code line

---

.github/workflows/main.yml

fix: modify  main.yml runs into gradle

---

.github/workflows/main.yml

CICD 적용을 위해 main branch에 테스트를 진행하기 위해 스크립트를 수정했습니다.

build: refactor main workflow

---

backend/src/main/java/ossproj/demo/dto/request/SignupRequest.java
backend/src/test/java/ossproj/demo/RecommendedApplicationTests.java

빌드를 위한  테스트 코드 제거
github action 빌드 실패로 인한 테스트 코드 제거

fix: 빌드를 위한  테스트 코드 제거

---

.github/workflows/backend-deployment.yml

build: java 배포판 변경

---

.github/workflows/backend-deployment.yml

fix: modify backend CD script

---

.github/workflows/backend-deployment.yml

fix: modify backend build directory

---

.github/workflows/backend-deployment.yml

`빌드성공`
CD 빌드시 워킹 디렉토리 에러 상황발생
디렉토리 코드 수정후 완료함
`오류상황`
`해결방법`
```
- name: Grant execute permission for gradlew
working-directory: backend < -해당코드 추가
run: chmod +x ./gradlew
- name: Convert line endings of gradlew
working-directory: backend < -해당코드 추가
run: sed -i 's/\r$//' ./gradlew
- name: Build with Gradle
working-directory: backend< -해당코드 추가
run: ./gradlew build
```

build: 백엔드 Code deploy + s3 배포완료

---

README.md

fix:README.md ml 추가

---

README.md

docs : ml 내용 추가

---

README.md

docs: README.md ml 수정

---

frontend/src/components/ResponsiveDrawer.tsx
frontend/src/index.tsx
frontend/src/pages/signup/index.tsx
frontend/src/query/queryKeys.ts

feat: 회원가입 ui publishing

---

frontend/.eslintrc.json
frontend/src/index.tsx
frontend/src/pages/signin/index.tsx
frontend/src/pages/signup/index.tsx
frontend/src/query/auth.ts
frontend/src/types/auth.ts

feat: 회원가입, 로그인 api 연동

---

frontend/src/components/ResponsiveDrawer.tsx
frontend/src/hooks/useSession.ts
frontend/src/index.tsx
frontend/src/query/auth.ts
frontend/src/query/queryKeys.ts
frontend/src/style.ts

feat: 인증 상태 ui 반영

---

backend/src/main/java/ossproj/demo/controller/UserController.java
backend/src/main/java/ossproj/demo/dto/request/auth/LoginRequest.java
backend/src/main/java/ossproj/demo/dto/request/auth/SignupRequest.java
backend/src/main/java/ossproj/demo/dto/response/SignupResponse.java
backend/src/main/java/ossproj/demo/entity/Users.java
backend/src/main/java/ossproj/demo/repository/UserRepository.java
backend/src/main/java/ossproj/demo/service/CustomUserDetailService.java
backend/src/main/java/ossproj/demo/service/UserServiceImpl.java

key value 값 프론트와 맞추기 위함
`student_id` : 학번 -> `studentNumber`로 변경

refactor: 학번 컬럼명 수정

---

frontend/src/components/TimeTable.tsx
frontend/src/pages/signin/index.tsx
frontend/src/pages/signup/index.tsx
frontend/src/pages/time-table/index.tsx
frontend/src/types/auth.ts

feat: ui improvement

---

backend/src/main/java/ossproj/demo/config/CorsConfig.java
backend/src/main/java/ossproj/demo/config/SecurityConfig.java

feat: cors 설정

---

frontend/src/pages/index.tsx

feat: improve writing

---

backend/src/main/java/ossproj/demo/config/SecurityConfig.java

fix: spring security cors 설정

---

backend/src/main/java/ossproj/demo/config/SecurityConfig.java

fix: Allow Origin 변경

---

frontend/src/components/ResponsiveDrawer.tsx
frontend/src/hooks/useSession.ts
frontend/src/pages/index.tsx
frontend/src/pages/signin/index.tsx
frontend/src/query/auth.ts
frontend/src/query/lecture.ts

feat: qa 개선사항 반영

---

LICENSE

docs: Add MIT LICENSE

---

dl/extract_DBrow_by_id.py

fix : DLserver index 수정
